2015/09/10 02:15:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1474): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yiitest\protected\controllers\TareasController.php(7): CActiveRecord->findAll()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TareasController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tareas/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tareas/index
---
2015/09/12 02:54:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 02:55:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 02:55:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 02:55:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1474): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\proyecto\protected\controllers\TareasController.php(8): CActiveRecord->findAll()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TareasController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tareas/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=tareas/index
---
2015/09/12 03:51:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 03:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 06:40:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 06:41:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 07:38:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 07:55:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 08:05:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
2015/09/12 08:07:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proyecto/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=proyecto/index
---
